// Generated by Selenium IDE
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using System.Collections.Generic;
using System.Threading;

[TestFixture]
public class P3RegistrarTrabajoRecepcionalPLADEAFEIExitosoTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;

    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }

    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }

    [Test]
    public void P3RegistrarTrabajoRecepcionalPLADEAFEIExitoso()
    {
        driver.Navigate().GoToUrl("https://localhost:5001/RegistrarTrabajoRecepcional");
        driver.Manage().Window.Size = new System.Drawing.Size(945, 1030);
        driver.FindElement(By.Id("inputNombreDeTrabajoRecepcional")).SendKeys("Modelado de sistemas con arquitectura de microservicios");
        {
            var dropdown = driver.FindElement(By.Id("TrabajoRecepcional_Modalidad"));
            dropdown.FindElement(By.XPath("//option[. = 'Monografía']")).Click();
        }
        driver.FindElement(By.Id("inputArchivoDeAnteproyecto")).SendKeys("C:\\ArchivosDePrueba\\Anteproyecto.pdf");
        driver.FindElement(By.Id("btnSeleccionarAlumnos")).Click();
        driver.FindElement(By.CssSelector("#tblAlumnos tr:nth-child(1) > td:nth-child(2)")).Click();
        driver.FindElement(By.Id("btnSeleccionarTipoDeProyecto")).Click();
        driver.FindElement(By.Id("selectSeleccionarTipoDeProyecto")).Click();
        {
            var dropdown = driver.FindElement(By.Id("selectSeleccionarTipoDeProyecto"));
            dropdown.FindElement(By.XPath("//option[. = 'PLADEAFEI']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("selectTipoDeProyecto"));
            dropdown.FindElement(By.XPath("//option[. = 'Programa estratégico 3. Apoyo al estudiante. Acción 7.3 Fomentar la participación de estudiantes en proyectos solicitados a los laboratorios de la FEI']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("IDLGACSeleccionadas"));
            dropdown.FindElement(By.XPath("//option[. = 'Gestión, Modelado y Desarrollo de Software']")).Click();
        }
        driver.FindElement(By.Id("inputLineaDeInvestigacion")).SendKeys("Diseño de Software, Ingeniería de requisitos");
        driver.FindElement(By.Id("btnSeleccionarOpcionDeSinodal")).Click();
        driver.FindElement(By.Id("btnBuscarSinodal")).Click();
        driver.FindElement(By.CssSelector("#tblIntegrantes tr:nth-child(2) > td:nth-child(3)")).Click();
        {
            var dropdown = driver.FindElement(By.Id("selectTipoDeSinodal"));
            dropdown.FindElement(By.XPath("//option[. = 'Director']")).Click();
        }
        driver.FindElement(By.Id("btnAñadirSinodal")).Click();
        driver.FindElement(By.CssSelector(".form-check-label")).Click();
        driver.FindElement(By.CssSelector("#tblSinodales tr:nth-child(3) > td:nth-child(3)")).Click();
        {
            var dropdown = driver.FindElement(By.Id("selectTipoDeSinodal"));
            dropdown.FindElement(By.XPath("//option[. = 'Codirector']")).Click();
        }
        driver.FindElement(By.Id("btnAñadirSinodal")).Click();
        driver.FindElement(By.Id("btnRegistrarTrabajoRecepcional")).Click();
        Thread.Sleep(4000);
        Assert.That(driver.FindElement(By.Id("h2MenuMaestro")).Text, Is.EqualTo("Menú maestro"));
    }
}
