// Generated by Selenium IDE
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using System.Collections.Generic;

[TestFixture]
public class P5RegistrarTrabajoRecepcionalSinSeleccionDeDirectorFallidoTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;

    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }

    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }

    [Test]
    public void P5RegistrarTrabajoRecepcionalSinSeleccionDeDirectorFallido()
    {
        driver.Navigate().GoToUrl("https://localhost:5001/RegistrarTrabajoRecepcional");
        driver.Manage().Window.Size = new System.Drawing.Size(945, 1030);
        driver.FindElement(By.Id("inputNombreDeTrabajoRecepcional")).SendKeys("Modelado de sistemas con arquitectura de microservicios");
        {
            var dropdown = driver.FindElement(By.Id("TrabajoRecepcional_Modalidad"));
            dropdown.FindElement(By.XPath("//option[. = 'Monografía']")).Click();
        }
        driver.FindElement(By.Id("inputArchivoDeAnteproyecto")).SendKeys("C:\\ArchivosDePrueba\\Anteproyecto.pdf");
        driver.FindElement(By.Id("btnSeleccionarAlumnos")).Click();
        driver.FindElement(By.CssSelector("#tblAlumnos tr:nth-child(1) > td:nth-child(2)")).Click();
        driver.FindElement(By.Id("btnSeleccionarTipoDeProyecto")).Click();
        {
            var dropdown = driver.FindElement(By.Id("selectSeleccionarTipoDeProyecto"));
            dropdown.FindElement(By.XPath("//option[. = 'Proyecto de investigación']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("selectTipoDeProyecto"));
            dropdown.FindElement(By.XPath("//option[. = 'Desarrollo de Software con una Arquitectura de Microservicios']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("IDLGACSeleccionadas"));
            dropdown.FindElement(By.XPath("//option[. = 'Gestión, Modelado y Desarrollo de Software']")).Click();
        }
        driver.FindElement(By.Id("inputLineaDeInvestigacion")).SendKeys("Diseño de software, Ingeniería de requisitos");
        driver.FindElement(By.Id("btnSeleccionarOpcionDeSinodal")).Click();
        driver.FindElement(By.Id("btnBuscarSinodal")).Click();
        driver.FindElement(By.CssSelector("#tblIntegrantes tr:nth-child(2) > td:nth-child(2)")).Click();
        {
            var dropdown = driver.FindElement(By.Id("selectTipoDeSinodal"));
            dropdown.FindElement(By.XPath("//option[. = 'Director']")).Click();
        }
        driver.FindElement(By.Id("btnRegistrarTrabajoRecepcional")).Click();
        Assert.That(driver.FindElement(By.CssSelector(".alert > label")).Text, Is.EqualTo("Debe seleccionar al menos un Director para el trabajo recepcional."));
    }
}
